languageCode = "en-us"
title = "Rita Kozlov"
theme = "coder"


paginate = 20 # Default number of pages per page in pagination.
canonifyurls = false # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.


disqusShortname = "ritakozlov" # Enable or disable Disqus

[params] # theme parameters
    author = "Rita Kozlov" # Author's name.
    info = "Cloudflare Worker 👩🏻‍🏭" # Author's job title or info.
    description = "Most cat pics" # Site description.
    keywords = "blog,developer,personal" # Site keywords.

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # RTL support
    rtl = false

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/rita3ko/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/ritakozlov_/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/ritakozlov/"
[[params.social]]
    name = "Instagram"
    weight = 3
    url = "https://www.instagram.com/lovelyreetah/"

# Menu links
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
